version: "3.1"

services:
  app:
    image: hangoverhgv/portfolio:20230310-03
    container_name: app
    ports:
      - 8080:5000
    depends_on:
      - mariadb
    environment:
      MARIADB_DATABASE:
      MARIADB_USER:
      MARIADB_PASSWORD:
      MARIADB_HOST:

  mariadb:
    image: mariadb:10.8.3-jammy
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_DATABASE:
      MARIADB_USER:
      MARIADB_PASSWORD:
